### ISSUE TITLE
Error getting inflation: ValueError: No tables found

### ISSUE THREAD

**Issue by chilango74** [mbk-dev/boi#5]
While getting inflation there is an error:
```
Traceback (most recent call last):
  File "C:\Users\Sergey\PycharmProjects\boi\main.py", line 12, in <module>
    abc = boi.infl.get_inflation()
  File "C:\Users\Sergey\PycharmProjects\boi\boi\infl.py", line 15, in get_inflation
    s = get_cp(datestart, dateend)
  File "C:\Users\Sergey\PycharmProjects\boi\boi\infl.py", line 9, in get_cp
    s = boi.request_data.get_data_frame(seriescode='CP', datestart=datestart, dateend=dateend, freq='M')
  File "C:\Users\Sergey\PycharmProjects\boi\boi\request_data.py", line 25, in get_data_frame
    ldf = pd.read_html(StringIO(resp))
  File "C:\Users\Sergey\AppData\Local\pypoetry\Cache\virtualenvs\boi-NXSF-JMz-py3.9\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Sergey\AppData\Local\pypoetry\Cache\virtualenvs\boi-NXSF-JMz-py3.9\lib\site-packages\pandas\io\html.py", line 1205, in read_html
    return _parse(
  File "C:\Users\Sergey\AppData\Local\pypoetry\Cache\virtualenvs\boi-NXSF-JMz-py3.9\lib\site-packages\pandas\io\html.py", line 1006, in _parse
    raise retained
  File "C:\Users\Sergey\AppData\Local\pypoetry\Cache\virtualenvs\boi-NXSF-JMz-py3.9\lib\site-packages\pandas\io\html.py", line 986, in _parse
    tables = p.parse_tables()
  File "C:\Users\Sergey\AppData\Local\pypoetry\Cache\virtualenvs\boi-NXSF-JMz-py3.9\lib\site-packages\pandas\io\html.py", line 262, in parse_tables
    tables = self._parse_tables(self._build_doc(), self.match, self.attrs)
  File "C:\Users\Sergey\AppData\Local\pypoetry\Cache\virtualenvs\boi-NXSF-JMz-py3.9\lib\site-packages\pandas\io\html.py", line 618, in _parse_tables
    raise ValueError("No tables found")
ValueError: No tables found
```

**Comment by fzhulitov** [comment]
Done
